Get http://localhost:8082/users

###

POST http://localhost:8082/users/email
Content-Type: application/json

{
    "Email": "johndoe2@gmail.com"
}

###

POST http://localhost:8082/users/password
Content-Type: application/json

{
    "Email": "johndoe2@gmail.com",
    "Password":  "986864656588"
}


###

Get http://localhost:8082/users/isAuthenticated
Content-Type: application/json


###

Get http://localhost:8082/users/logout

###

POST http://localhost:8082/users/adduser
Content-Type: application/json

{
    "Email": "johndoe2@gmail.com",
    "Password":  "986864656588"
}
